name = "Theme"
license = "MIT"
licenselink = ""
description = ""
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = ""
    homepage = ""

# If Porting existing theme
[original]
    author =  ""
    homepage = ""
    repo = ""
